### ISSUE TITLE
Linked sites without button

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#1]
![image](https://user-images.githubusercontent.com/7252105/56722959-57366680-6748-11e9-9ddc-90fd79603f31.png)

I remember you mentioned that something needs to be done on the websites that you link to to avoid the button. Can you let me know what this is exactly so I can try to arrange this for the Academy.

Probably we will need an option in that window to show it in full screen mode as well.

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
The design of the portal was slightly changed as well as the lateral menu. Currently, to avoid the button we did a change in the behaviour of this component, so now this opens the tool in another tab of the browser instead of open a view with a button. However, if you want to integrate the tools in the portal view as an iframe (see the picture using TASKA as an example), you need to add the EHDEN Portal URL as a trusted server in the system configuration of each tool.

![taska](https://user-images.githubusercontent.com/17878072/60663251-91ae3500-9e56-11e9-81a0-b18148604ddc.png)

**Comment by PRijnbeek** [comment]
Can explain this a bit better to me. Suppose I like to add the Academy as an iframe what do I have to do for that to work? I depends a bit on the functionality of the side bar if it will make sense but the user experience is nicer if all is in the website i think instead of in another tab? What do you think?

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I think this issue was already discussed in the past and we may forget to close it. The more usable solution was to open the applications in a new window (or tab) without iFrame it inside the portal, mainly due to the visual complexity of having one application inside another. It is not a technical issue, it is more a usability issue. If you do not agree, we can open this issue again.
