### ISSUE TITLE
Layout suggestion

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#13]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/7252105/66078109-aedfc600-e561-11e9-9bc2-550057b8fa04.png">

I suggest we do not use questions when we view the data. For example "when was the first version created?" should be "Date first CDM version"

I would remove the question numbers when you view the questionnaire (not when you edit?).

The elements take up a lot of space, for example it shows the options that are not selected.

How about this (but than as two columns):

First CDM Version                                        12/01/2015
Database Managment System                    Postgresql, [other options selected]

As the default view (a bit like the summary view but then not as a table)?
The current view feels to me as the "Edit mode" view.

I like the comment field next to it. The "This question has an answer" seems a bit less useful for me in the UI.

Cannot judge how big this change would be and curious how you see this.

**Comment by joaorafaelalmeida** [comment]
I think this issue can be closed due to the updates in the fingerprint view made regarding other issues and in the questionnaire structure. In the questionnaire, as we have been discussing over the last weeks/months, the questions were changed to have more user-friendly labels instead of pure questions.
