### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#38]
I have this problem.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/7252105/86034051-36e3f500-ba3a-11ea-8e68-0990e5906610.png">

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
Could you provide more details about this issue? Did you tried to install the system locally and then you got this issue?
I am asking this because this kind of view for errors only happens in development mode or inside some plugins (and in this case, the issue is related to the plugin itself, for instance, superset, etc.).

**Comment by PRijnbeek** [comment]
This was on the production version, but seems to have fixed itself?
