### ISSUE TITLE
Questionnaire Issues

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#45]
2.04 
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7252105/94371889-14757c80-00fa-11eb-811e-efbf4522034c.png">

I assume you do not have to fill in the Region, since for example for IPCI this is multiple areas in The Netherlands.? 

2.05 +2.11 + 3.02 (and check the other questions too please i did not try all)
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7252105/94371925-5acadb80-00fa-11eb-8c6d-e11734456575.png">

When I select Other I cannot fill in anything

2.06
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7252105/94371946-7635e680-00fa-11eb-8100-2248d0344867.png">

Here the freetext box is visible by default even without selecting "other"

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
This "bug" was originated because of the question types chosen in the questionnaire. I already harmonize this by changing them to the correct type. This way, every time the user chooses the option "Other", a free text box is presented. 
Regarding question 2.04, you can only specify the country, but this is not a mandatory question.
Please check if everything is as you expected.
