### ISSUE TITLE
Concept Browser table

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#58]
Can you explain how this table is created. There should be a query somewhere that creates the magnitude etc on the fly when new data is uploaded. 

We like to change this so this is happening in CatalogExport already so this detailed information does not have to be shared by the data source.

**Comment by joaorafaelalmeida** [comment]
Hi Peter,

To answer your question I did these two figures that will help me explaining the current workflow. This first image shows the initial workflow in which the Achilles results were uploaded in the EHDEN Portal, then loaded into a Postgres database, and finally, this data could be accessed by Superset. Then, you performed your queries in the SQL Lab and customized your charts/dashboards. However, every time we open those charts, Superset executes the query you defined in the SQL Lab, which takes some time to fulfil the data in the charts.

![Dashboard1](https://user-images.githubusercontent.com/17878072/98709216-ff873c80-2379-11eb-8f84-ee7de9e4820b.png)

The solution was the creation of Materialized views, in which we copy the queries you used in your chart to a console. This way, superset render the charts much faster, because instead of performing the queries and getting the results, Superset already receives the data prepared to be rendered. You can continue to use the old pipeline to create your charts. Usually, we only create materialized views from your queries when you finish the dashboard.

![Dashboard2](https://user-images.githubusercontent.com/17878072/98709723-ad92e680-237a-11eb-9db7-1ee4a8bac8ff.png)

Therefore, the query that you want to changes is the following:
```sql
SELECT
    q1.concept_id AS concept_id,
    q1.concept_name AS concept_name,
    q1.domain_id,
    source.name AS source_name,
    source.acronym,
    sum(q1.count_value) as "Occurrence_count",
    sum(q1.count_person) as "Person_count",
    CASE 
        WHEN sum(q1.count_value)<=10 THEN '<=10'
        WHEN sum(q1.count_value)<=100 THEN '11-10ˆ2'
        WHEN sum(q1.count_value)<=1000 THEN '10ˆ2-10ˆ3'
        WHEN sum(q1.count_value)<=10000 THEN '10ˆ3-10ˆ4'
        WHEN sum(q1.count_value)<=100000 THEN '10ˆ4-10ˆ5'
        WHEN sum(q1.count_value)<=1000000 THEN '10ˆ5-10ˆ6'
        ELSE '>10ˆ6'
    END as "magnitude_occurrences",
    CASE 
        WHEN sum(q1.count_person)<=10 THEN '<=10'
        WHEN sum(q1.count_person)<=100 THEN '11-10ˆ2'
        WHEN sum(q1.count_person)<=1000 THEN '10ˆ2-10ˆ3'
        WHEN sum(q1.count_person)<=10000 THEN '10ˆ3-10ˆ4'
        WHEN sum(q1.count_person)<=100000 THEN '10ˆ4-10ˆ5'
        WHEN sum(q1.count_person)<=1000000 THEN '10ˆ5-10ˆ6'
        ELSE '>10ˆ6'
    END AS "magnitude_persons"
FROM (SELECT analysis_id,
             stratum_1 concept_id,
             data_source_id,
             concept_name,
             domain_id,
             count_value, 0 as count_person
    FROM achilles_results
    JOIN concept ON cast(stratum_1 AS BIGINT)=concept_id
    WHERE analysis_id in (201, 301, 401, 601, 701, 801, 901, 1001, 1801)
    UNION (SELECT  analysis_id,
                   stratum_1 concept_id,
                   data_source_id,
                   concept_name,
                   domain_id,
                   0 as count_value,
                   sum(count_value) as count_person
            FROM  achilles_results
            JOIN concept on cast(stratum_1 as BIGINT)=concept_id
            WHERE analysis_id in (202, 401, 601, 701, 801, 901, 1001, 1801)
            GROUP BY analysis_id,stratum_1,data_source_id,concept_name,domain_id) ) as q1
    INNER JOIN public.data_source AS source ON q1.data_source_id=source.id
GROUP BY q1.concept_id,q1.concept_name,q1.domain_id,source.name, acronym
ORDER BY "Person_count" desc
```

**Comment by joaorafaelalmeida** [comment]
If you have any question, please let me know.

**Comment by PRijnbeek** [comment]
Thanks. If I upload a new database / version will that view that automatically be updated?

@solventrix I you can update the query in CatalogueExport with the one above i think we are all set. @joaorafaelalmeida can then simplify his query that generates the View.

**Comment by joaorafaelalmeida** [comment]
Yes. The only manual part is the creation of the materialized view. If you update or add a new data source, after a few seconds, the dashboards will be updated with the new information. Can I close this issue?

**Comment by PRijnbeek** [comment]
Ok thanks

**Comment by asancas23** [comment]
Hi guys,
Let's see if you can help me with a problem that I am encountering with the visualization of data in the EHDEN Portal (https://portal.ehden.eu/).
I have uploaded the Catalog Export csv file and almost all the data is displayed except in the Concept Browser where we do not see anything.
You know that it may be due?.

Regards,
